config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'
  resources :contacts
  resources :agents do
    member do
      get '/set_default_contact', to: "agents#set_default_contact"
    end
  end
end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_many :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :agent

  def assign_agent(id)
    self.agent_id = id
    self.save
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:edit, :update, :destroy, :show, :set_default_contact]

  def index
    @agents = Agent.all
  end

  def new
    @agent = Agent.new    
  end

  def create
    @agent = Agent.create(name: params[:agent][:name])
    redirect_to agents_path
  end

  def edit; end

  def update
    @agent.update(name: params[:agent][:name])
    redirect_to agents_path
  end

  def destroy
    @agent.contacts.each.map(&:destroy)
    @agent.destroy
    redirect_to agents_path
  end

  def show; end

  def set_default_contact
    @agent.update(default_contact_id: params[:contact_id])
    redirect_to agent_path(params[:id])
  end

  private

  def set_agent
    @agent = Agent.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:edit, :update, :destroy, :show]

  def index
    @contacts = Contact.all  
  end

  def new
    @contact = Contact.new  
  end

  def create
    unless params[:contact][:agent].blank?
      @contact = Contact.create(email: params[:contact][:email]) 
      @contact.assign_agent(params[:contact][:agent])
    end

    redirect_to contacts_path
  end

  def edit; end

  def update
    @contact.update(email: params[:contact][:email]) 
    @contact.assign_agent(params[:contact][:agent])

    redirect_to contacts_path
  end

  def destroy
    @contact.destroy

    redirect_to contacts_path
  end

  def show; end

  private

  def set_contact
    @contact = Contact.find(params[:id]) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/_form.html.haml
= form_for @agent do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/agents/edit.html.haml
= render 'form'

app/views/agents/index.html.haml
= link_to "list all agent", agents_path
= link_to "list all contact", contacts_path
%p= link_to "new agent", new_agent_path
- @agents.each do |agent|
  = agent.name
  = link_to "destroy", agent_path(agent), method: "delete"
  = link_to "edit", edit_agent_path(agent)
  = link_to "show", agent_path(agent)
  %p

app/views/agents/new.html.haml
= render 'form'

app/views/agents/show.html.haml
= link_to "list all agent", agents_path
= link_to "list all contact", contacts_path
%h1= @agent.name
- @agent.contacts.each do |contact|
  %p
    = "(default)" if @agent.default_contact_id == contact.id
    = contact.email
    = link_to "set as default", set_default_contact_agent_path(@agent, contact_id: contact.id) 

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  = f.label :email
  = f.text_field :email
  = f.label :agent
  = f.select(:agent, options_from_collection_for_select(Agent.all, :id, :name, @contact.try(:agent).try(:id)), include_blank: true)
  = f.submit

app/views/contacts/edit.html.haml
= render 'form'

app/views/contacts/index.html.haml
= link_to "list all agent", agents_path
= link_to "list all contact", contacts_path
%p= link_to "new contact", new_contact_path
- @contacts.each do |contact|
  = contact.email
  = link_to contact.agent.name, agent_path(contact.agent)
  = link_to "destroy", contact_path(contact), method: "delete"
  = link_to "edit", edit_contact_path(contact)
  = link_to "show", contact_path(contact)
  %p

app/views/contacts/new.html.haml
= render 'form'

app/views/contacts/show.html.haml
= @contact.email
= "belongs_to"
= @contact.agent.name

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JCM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>